FPS_LIMIT = 60
WINDOW_SIZE = (1280, 720)
GAME_TITLE = "Mahjong Riichi"

TILES_IMAGE_LINK = "images/tiles/sheet.png"
TILE_SCALE_BY = 2.0
TILE_ANIMATION_DURATION = 0.5
TILE_POPUP_DURATION = 1
TILE_WIDTH = 32
TILE_HEIGHT = 32

DIRECTION_IMAGE_LINK = "images/directions/direction.png"
DIRECTION_WIDTH = 32
DIRECTION_HEIGHT = 32

TURN_BAR_HEIGHT = 10

CENTER_BOARD_FIELD_SIZE = (540, 540)
DIRECTION_TURN_SIZE = (180, 180)
DISCARD_FIELD_SIZE = (180, 180)
